// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXrdj2_q1Vp-8DPNQmIaBdJS6M-LsL5c0',
    appId: '1:350924770863:android:e72b8dbcca5a48bc6e80da',
    messagingSenderId: '350924770863',
    projectId: 'timelyy-cce37',
    storageBucket: 'timelyy-cce37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1AmGeBdGytoNpp4B49VMi4y7JVmpgjoE',
    appId: '1:350924770863:ios:29dffb2bc4e2663a6e80da',
    messagingSenderId: '350924770863',
    projectId: 'timelyy-cce37',
    storageBucket: 'timelyy-cce37.firebasestorage.app',
    iosBundleId: 'com.example.timely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARYLVEMGumXqyu_PWQxXWGqUOGwN70s30',
    appId: '1:350924770863:web:ea0d3c14d6bfaaad6e80da',
    messagingSenderId: '350924770863',
    projectId: 'timelyy-cce37',
    authDomain: 'timelyy-cce37.firebaseapp.com',
    storageBucket: 'timelyy-cce37.firebasestorage.app',
    measurementId: 'G-ZL871X394B',
  );
}
