name: Flutter Build (macOS - Android/iOS/Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Build Android APK
      run: flutter build apk --release

    - name: Build iOS (no codesign)
      run: flutter build ios --release --no-codesign

    - name: Build Windows
      run: flutter build windows --release
